version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    groups:
      github-actions-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    groups:
      cargo-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /desktop
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    groups:
      desktop-cargo-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
      time: "04:40"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    groups:
      gradle-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
