[package]
name = "enigma-sodium"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
libsodium-sys-stable = { version = "=1.24.0", default-features = false }
