[package]
name = "enigma-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "=0.22.1"
enigma-protocol = { path = "../enigma-protocol" }
enigma-sodium = { path = "../enigma-sodium" }
qrcode = { version = "=0.14.1", default-features = false }
